import { Locator, Page, expect } from "@playwright/test";
import ApplicationURL from "../helpers/ApplicationURL";
import fakeData from "../helpers/faker";
import Utils from "../helpers/Utils";

/**
 * Class representing the Cart Page.
 */
export default class CartPage {
  private orderButton: Locator;
  private utils: Utils;
  /**
   * Creates an instance of CartPage.
   * @param {Page} page - The Playwright Page object.
   */
  constructor(protected page: Page) {
    this.orderButton = page.getByRole("button", { name: "Place Order" });
    this.utils = new Utils(page);
  }

  /**
   * Places an order on the cart page and verifies the confirmation details.
   *
   * 1. Clicks the "Place Order" button.
   * 2. Waits for the order modal to appear.
   * 3. Fills in the order form with random data generated by Faker.
   * 4. Submits the form by clicking the "Purchase" button.
   * 5. Verifies that the confirmation alert contains the correct details.
   *
   */
  public async placeOrderAndVerify() {
    // Click the "Place Order" button
    await this.orderButton.click();

    // Wait for the order modal to appear
    const modal = await this.utils.waitForModal("#orderModal.modal.show");

    // Fill in the form with the Faker-generated data
    await this.page.fill("#name", fakeData.NAME);
    await this.page.fill("#country", fakeData.COUNTRY);
    await this.page.fill("#city", fakeData.CITY);
    await this.page.fill("#card", fakeData.CARD);
    await this.page.fill("#month", fakeData.MONTH);
    await this.page.fill("#year", fakeData.YEAR);

    // Click the "Purchase" button
    await this.page.getByRole("button", { name: "Purchase" }).click();

    // Use the utility method to wait for and verify the alert
    const alert = await this.utils.waitForModal(
      ".sweet-alert.showSweetAlert.visible"
    );

    // Wait for the confirmation alert to appear
    await this.utils.verifyText(
      alert.locator("h2"),
      "Thank you for your purchase!"
    );
    await this.utils.verifyText(
      alert.locator(".lead.text-muted"),
      `Card Number: ${fakeData.CARD}`
    );
    await this.utils.verifyText(
      alert.locator(".lead.text-muted"),
      `Name: ${fakeData.NAME}`
    );
  }
}
